Node permissioning
ConsenSys/quorum pull request #2
Opened 2016-11-15 04:21 UTC by ssudhir123

2016-11-15 05:25 UTC, chetan requested changes
Looks good for the most part, see minor comments. Will test tomorrow and update again

2016-11-15 05:25 UTC, chetan commented on permissioned-nodes.json
> +]
I guess this file is meant as a sample? Is there a better place to put it?

2016-11-15 05:25 UTC, chetan commented on p2p/permissions.go
> +func main() {
This `main()` method looks to be left over from testing.. remove

2016-11-15 14:27 UTC, patrickmn requested changes

2016-11-15 14:27 UTC, patrickmn commented on README.md
> +  --enableNodePermission      Enables node permissioning. If true, it reads from <datadir>/permissioned-nodes.json and allowws only those nodes to connect
Rename to --permissioned

2016-11-15 14:27 UTC, patrickmn commented on p2p/permissions.go
> +	nodes := parsePermissionedNodes(datadir)
This shouldn't happen every time there's a check. Can e.g. "Permissioner" be a service that's spun up and does the parsing once at startup?

2016-11-15 14:29 UTC, patrickmn commented
Generally looks good, I'd say just change the flag name to permissioned, remove main() and change the contents of the sample file. Making it a service/not re-parsing every request can happen later.

2016-11-15 19:05 UTC, patrickmn requested changes

2016-11-15 19:05 UTC, patrickmn commented on README.md
> +  --permission      Enables node permissioning. If true, it reads from <datadir>/permissioned-nodes.json and allowws only those nodes to connect
--permissioned, also note the spacing

2016-11-15 19:05 UTC, patrickmn commented on README.md
> +Node Permissioning is a features that controls which nodes can connect to a given node and also to which nodes this node can dial out to. Currently, it is managed at individual node level by a comman
feature
"to which other nodes this one will connect"
at an individual node level
--permissioned

2016-11-15 19:05 UTC, patrickmn commented on README.md
> +If the "--permission" node is present, the node looks for a file named "<data-dir>/permissioned-nodes.json". This file contains the list of enodes specified that this node can connect to and also acc
--permissioned
If the permission is specified -> If permissioning is enabled

2016-11-15 19:05 UTC, patrickmn commented on README.md
> +In the current release, every node has its own copy of the permissioned-nodes.json. It is understood that if different nodes have different list of remote keys. In future releases, the permissioned n
It is understood... -> "This copy should be the same for all nodes in the network"?

2016-11-16 11:49 UTC, tylobban commented on README.md
> +  --permission      Enables node permissioning. If true, it reads from <datadir>/permissioned-nodes.json and allowws only those nodes to connect
should this be 'permission**ed**', per the Name value of the EnableNodePermissionFlag flag?

Minor spelling mistake in the comment allowws -> allows

2016-11-16 11:57 UTC, tylobban commented on README.md
> +Node Permissioning is a features that controls which nodes can connect to a given node and also to which nodes this node can dial out to. Currently, it is managed at individual node level by a comman
--permission**ed**

2016-11-18 15:18 UTC, patrickmn commented
Merged in https://github.com/jpmorganchase/quorum/pull/15

2016-11-18 15:18 UTC, closed without merging